services:
  jellyseerr:
    image: fallenbagel/jellyseerr:preview-OIDC
    container_name: jellyseerr
    environment:
      #- LOG_LEVEL=debug
      - TZ=Australia/Sydney
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /data/jellyseerr:/app/config
    restart: unless-stopped