services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    runtime: nvidia
    network_mode: host
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=Australia/Sydney
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - JELLYFIN_PublishedServerUrl=https://jellyfin.yourdomain.tld #optional
    volumes:
      - /data/jellyfin:/config
      - /mnt/media/anime:/media/anime:ro
      - /mnt/media/movies:/media/movies:ro
      - /mnt/media/movies4k:/media/movies4k:ro
      - /mnt/media/music:/media/music:ro
      - /mnt/media/tvshows:/media/tvshows:ro
    devices:
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD129:/dev/dri/renderD129
    restart: unless-stopped
networks: {}