services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=Australia/Sydney
    volumes:
      - /data/sonarr:/config
      - /mnt/media/tvshows:/media/tvshows
      - /mnt/media/anime:/media/anime
      - /mnt/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped