http:
  middlewares:
    qb-headers:
      headers:
        customRequestHeaders:
          X-Frame-Options: 'SAMEORIGIN'
          Referer: ''
          Origin: ''

    deluge-role:
      plugin:
        validate-headers:
          headers:
            - name: 'X-Oidc-Roles'
              matchtype: one
              values:
                - '"admin"'
                - '"deluge"'
              regex: false
              contains: true
              required: true

  routers:
    # 1) Internal-only router: bypass OIDC for private IPs
    deluge-internal:
      rule: 'Host(`deluge.yourdomain.tld`) && (ClientIP(`10.0.0.0/8`) || ClientIP(`172.16.0.0/12`) || ClientIP(`192.168.0.0/16`) || ClientIP(`127.0.0.0/8`))'
      service: deluge
      tls: {}
      priority: 100

    # 2) External router: enforce OIDC + role for all others
    deluge:
      rule: 'Host(`deluge.yourdomain.tld`)'
      service: deluge
      tls: {}
      middlewares:
        - qb-headers
        - oidc-auth
        - deluge-role
      priority: 10

  services:
    deluge:
      loadBalancer:
        servers:
          - url: 'http://10.0.0.2:8112'
