http:
  routers:
    home-assistant:
      rule: "Host(`hass.yourdomain.tld`)"
      service: home-assistant
      tls: {}

  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: "http://10.0.0.200:8123"
