http:
  routers:
    plex:
      rule: 'Host(`plex.yourdomain.tld`)'
      service: plex
      tls: {}

  services:
    plex:
      loadBalancer:
        servers:
          - url: 'http://10.0.0.2:32400'
