services:
  beets-flask:
    image: pspitzner/beets-flask:stable
    restart: unless-stopped
    container_name: beets-flask
    ports:
      - 8337:5001
    environment:
      # Change to your timezone
      TZ: Australia/Sydney
      # 502 is default on macos, 1000 on linux
      USER_ID: 1500
      GROUP_ID: 1000
      BEETSDIR: "/config"
    volumes:
      - /data/beets:/config
      - /mnt/media/music:/media/music
      - /mnt/downloads:/downloads #optional
networks: {}
