services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=Australia/Sydney
    volumes:
      - /data/bazarr:/config
      - /mnt/media/anime:/media/anime
      - /mnt/media/movies:/media/movies
      - /mnt/media/movies4k:/media/movies4k
      - /mnt/media/tvshows:/media/tvshows
    ports:
      - 6767:6767
    restart: unless-stopped